### ISSUE TITLE
Sensei

### ISSUE THREAD

**Issue by dapoadedire** [Frokesy/react-libraries-playground#1]
When you go teach me, boss?

**Comment by Frokesy** [comment]
> When you go teach me, boss?

I literally just started😂

**Comment by dapoadedire** [comment]
'git push' asap abeg.
Make I quickly fork & clone am 😂 😂

**Comment by Frokesy** [comment]
> 'git push' asap abeg.
> 
> Make I quickly fork & clone am 😂 😂 

I don't have much there yet😂
